apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: payment-service-dr
  namespace: {{ .Values.namespace }}
spec:
  host: payment-service.{{ .Values.namespace }}.svc.cluster.local

  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutive5xxErrors: 2
      interval: 5s
      baseEjectionTime: 30s
      maxEjectionPercent: 100

  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2

