apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: payment-jwt
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: payment-service
  jwtRules:
  - issuer: "{{ .Values.jwt.issuer }}"


